import{useEffect,useMemo,useState}from'react';
import{ArrowRight,ExternalLink,GitBranch,Network,RefreshCw,ScanSearch,ShieldCheck,Wallet}from'lucide-react';
import type{CalldataEncodable}from'genlayer-js/types';
import{CONTRACT,configured,connectWallet,explorer,readFinalized,short,txUrl,writeFinalized}from'./genlayer';
import{citationPmid,writeWithReadback}from'./actions';

type Log={label:string;hash:string};type Claim={id:number;text:string;status:string;revision:number;citations:string[];parents:number[];reason:string;last_assessment_id?:number};
const fixture={article:'27516793',notice:'28515760',child:'322561',replacement:'10969679'};
export default function App(){
 const[account,setAccount]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');const[logs,setLogs]=useState<Log[]>([]);const[counts,setCounts]=useState<any>(null);const[protocol,setProtocol]=useState<any>(null);const[workspaceId,setWorkspaceId]=useState('1');const[claimId,setClaimId]=useState('1');const[workspace,setWorkspace]=useState<any>(null);const[claims,setClaims]=useState<Claim[]>([]);const[assessment,setAssessment]=useState<any>(null);
 const wid=Number(workspaceId)||0;
 const sync=async()=>{if(!configured)return;setError('');try{const[p,c,w]=await Promise.all([readFinalized<any>('get_protocol'),readFinalized<any>('get_counts'),wid?readFinalized<any>('get_workspace',[wid]):null]);setProtocol(p);setCounts(c);setWorkspace(w);const ids=(w?.claim_ids||[]) as number[];const loaded=await Promise.all(ids.map(id=>readFinalized<Claim>('get_claim',[id])));setClaims(loaded);const latest=Math.max(Number(w?.last_assessment_id)||0,...loaded.map(claim=>Number(claim.last_assessment_id)||0));if(latest)setAssessment(await readFinalized('get_assessment',[latest]));else setAssessment(null)}catch(e){setError(message(e))}};
 useEffect(()=>{void sync()},[]);
 const connect=async()=>{setError('');try{setAccount(await connectWallet())}catch(e){setError(message(e))}};
 const send=async(label:string,fn:string,args:CalldataEncodable[])=>{setBusy(label);setError('');try{if(!account)throw Error('Connect a wallet before signing.');const hash=await writeWithReadback(account,fn,args,{read:readFinalized,write:writeFinalized});setLogs(v=>[{label,hash},...v]);await sync()}catch(e){setError(message(e))}finally{setBusy('')}};
 const create=async()=>{setBusy('Create workspace');setError('');try{if(!account)throw Error('Connect a wallet before signing.');const hash=await writeWithReadback(account,'create_workspace',['Cardiac evidence lineage'],{read:readFinalized,write:writeFinalized});setLogs(v=>[{label:'Create workspace',hash},...v]);const freshCounts=await readFinalized<any>('get_counts');const next=Number(freshCounts.workspaces);const freshWorkspace=await readFinalized<any>('get_workspace',[next]);setCounts(freshCounts);setWorkspaceId(String(next));setWorkspace(freshWorkspace);setClaims([]);setAssessment(null)}catch(e){setError(message(e))}finally{setBusy('')}};
 const addFirst=()=>send('Add root claim','add_claim',[wid,'A left ventricular pseudoaneurysm may appear as a lung mass after cardiac surgery.']);
 const addSecond=()=>send('Add downstream claim','add_claim',[wid,'Diagnostic guidance should explicitly consider cardiac pseudoaneurysm in this presentation.']);
 const graphIds=(workspace?.claim_ids||[]) as number[];
 const citation=()=>send('Add citation','add_citation',[Number(claimId),citationPmid(Number(claimId),Number(graphIds[0]),fixture.article,fixture.child)]);
 const dependency=()=>{if(graphIds.length<2)return setError('Add and sync two claims before linking them.');void send('Link dependency','add_dependency',[graphIds[0],graphIds[1]])};const seal=()=>send('Seal graph','seal_workspace',[wid]);const assess=()=>send('Assess notice','assess_notice',[wid,fixture.article,fixture.notice]);
 const selected=claims.find(c=>c.id===Number(claimId));const verify=()=>send('Verify selected support','verify_claim_support',[Number(claimId),Number(selected?.revision||0)]);const replacement=()=>send('Add replacement','add_citation',[Number(claimId),fixture.replacement]);const reassess=()=>send('Reassess branch','reassess_claim',[Number(claimId),Number(selected?.revision||0)]);
 const edges=useMemo(()=>claims.flatMap(c=>c.parents.map(p=>`${p} → ${c.id}`)),[claims]);
 return <><header><a className="brand" href="#top"><img src="/retractgraph-logo.png"/><span>RetractGraph<small>Scientific Evidence Cascade</small></span></a><nav><a href="#graph">Graph</a><a href="#scanner">Notice scanner</a><a href="#audit">Audit</a></nav><span className="network"><i/>Studio Next · 61997</span><button className="outline" onClick={connect}><Wallet size={16}/>{account?short(account):'Connect wallet'}</button></header>
 {error&&<div className="error">{error}</div>}<main id="top"><section className="hero"><div><p className="eyebrow">PUBMED-GROUNDED · VALIDATOR-VERIFIED</p><h1>When evidence breaks,<br/><em>trace what changes.</em></h1><p className="lead">Build a claim lineage graph. Verify an exact PubMed retraction or correction. RetractGraph marks the affected evidence edge and creates a deterministic recheck wave—without declaring every downstream claim false.</p><div className="actions"><a className="primary" href="#graph">Open graph console <ArrowRight size={17}/></a><a className="outline" href="https://pubmed.ncbi.nlm.nih.gov/28515760/" target="_blank">View canonical notice <ExternalLink size={15}/></a></div></div><div className="visual"><img src="/retractgraph-logo.png"/><div><b><ShieldCheck/>Fixed authority</b><span>NCBI PubMed E-utilities</span></div><div><b><GitBranch/>Persistent consequence</b><span>Bounded impact propagation</span></div></div></section>
 <section className="metrics"><div><b>{counts?.workspaces||0}</b><span>Workspaces</span></div><div><b>{counts?.claims||0}</b><span>Claims</span></div><div><b>{counts?.assessments||0}</b><span>Assessments</span></div><div><b>{protocol?.custody?'Yes':'No'}</b><span>Fund custody</span></div></section>
 <section id="graph" className="section"><div className="sectionHead"><div><p className="eyebrow">PERMISSIONLESS WORKSPACE</p><h2>Build the evidence lineage</h2></div><button className="outline" onClick={sync}><RefreshCw size={16}/>Read finalized state</button></div>{!configured&&<div className="warning">Deploy the contract, then set <code>VITE_CONTRACT_ADDRESS</code>. No fallback address is embedded.</div>}<div className="consoleGrid"><article className="panel"><h3>1. Graph author</h3><p>Any wallet can create a graph. Link dependencies first, then validators verify every claim's complete citation set before sealing.</p><button disabled={!configured||!!busy} className="primary full" onClick={create}>Create sample workspace</button><label>Workspace ID<input value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}/></label><div className="twins"><button disabled={!!busy} onClick={addFirst}>Add root claim</button><button disabled={!!busy} onClick={addSecond}>Add downstream</button></div><label>Claim ID<input value={claimId} onChange={e=>setClaimId(e.target.value)}/></label><button disabled={!!busy} className="outline full" onClick={citation}>Add canonical PMID</button><button disabled={!!busy} className="outline full" onClick={dependency}>Link claim 1 → 2</button><button disabled={!!busy||!selected} className="outline full" onClick={verify}>Verify selected support</button><button disabled={!!busy} className="dark full" onClick={seal}>Seal verified graph</button></article><article className="panel graph"><h3>Authoritative graph</h3><div className="graphMeta"><span>Workspace #{wid}</span><b className={`badge ${workspace?.status||''}`}>{workspace?.status||'NOT LOADED'}</b></div>{claims.length?claims.map(c=><div className={`node ${c.status}`} key={c.id}><span>#{c.id}</span><div><b>{c.text}</b><small>{c.citations.join(', ')} · rev {c.revision}</small><em>{c.status} · {c.reason}</em></div></div>):<p className="empty">Create or load a workspace to see its claim graph.</p>}<div className="edges">{edges.map(x=><code key={x}>{x}</code>)}</div></article></div></section>
 <section id="scanner" className="section alt"><p className="eyebrow">PERMISSIONLESS ASSESSMENT</p><h2>Verify a notice, then repair the branch</h2><p className="sectionLead">A steward may connect any wallet and assess a sealed public graph. Only graph construction remains creator-controlled.</p><div className="cards"><article><ScanSearch/><h3>Canonical pair</h3><dl><dt>Article PMID</dt><dd>{fixture.article}</dd><dt>Notice PMID</dt><dd>{fixture.notice}</dd></dl><button disabled={!!busy} className="danger full" onClick={assess}>{busy==='Assess notice'?'Waiting for finality…':'Assess retraction impact'}</button></article><article><Network/><h3>Repair selected claim</h3><p>Add PMID {fixture.replacement} and ask validators whether the resulting citation set still supports the exact claim.</p><div className="twins"><button disabled={!!busy} onClick={replacement}>Add replacement</button><button disabled={!!busy} onClick={reassess}>Reassess</button></div></article><article><ShieldCheck/><h3>Latest assessment</h3><dl><dt>Status</dt><dd>{assessment?.status||'Not assessed'}</dd><dt>Relation</dt><dd>{assessment?.relation||'—'}</dd><dt>Requester</dt><dd>{short(assessment?.requester||'')}</dd><dt>Reason</dt><dd>{assessment?.reason||'—'}</dd></dl></article></div></section>
 <section id="audit" className="section"><p className="eyebrow">REVIEWER AUDIT TRAIL</p><h2>Trust the readback, not the interface</h2><div className="audit"><div><span>Contract</span><code>{configured?CONTRACT:'Not deployed'}</code>{explorer&&<a href={explorer} target="_blank">Explorer <ExternalLink size={14}/></a>}</div><div><span>Source</span><a href={`https://pubmed.ncbi.nlm.nih.gov/${fixture.notice}/`} target="_blank">PubMed notice {fixture.notice} <ExternalLink size={14}/></a></div><div><span>Snapshot digest</span><code>{assessment?.source_digest||'Available after assessment'}</code></div></div><div className="logs">{logs.map(l=><a href={txUrl(l.hash)} target="_blank" key={l.hash}><span>{l.label}</span><code>{short(l.hash)}</code><ExternalLink size={14}/></a>)}</div><p className="disclaimer">PubMed records bibliographic metadata and notice relationships. RetractGraph does not certify scientific truth and is not medical advice. PubMed Disclaimer applies.</p></section></main><footer><b>RetractGraph</b><span>Open source evidence lineage on GenLayer.</span></footer></>;
}
function message(e:unknown){return e instanceof Error?e.message:String(e)}
