#!/usr/bin/env node
import{createAccount,createClient}from'../frontend/node_modules/genlayer-js/dist/index.js';import{studioDevnet}from'../frontend/node_modules/genlayer-js/dist/chains/index.js';
const CONTRACT=process.argv[2],wid=Number(process.argv[3]||1),c1=Number(process.argv[4]||1),c2=Number(process.argv[5]||2);if(!/^0x[0-9a-fA-F]{40}$/.test(CONTRACT||''))throw Error('contract address required');
const chain={...studioDevnet,id:61997,name:'Studio Next',rpcUrls:{default:{http:['https://studio-next.genlayer.com/api']}}};
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');let value='';const done=()=>{process.stdin.off('data',onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==='\u0003'){done();reject(Error('Interrupted'));return}if(ch==='\r'||ch==='\n'){done();process.stdout.write('\n');resolve(value.trim());return}if(ch==='\u007f'||ch==='\b')value=value.slice(0,-1);else value+=ch}};process.stdin.on('data',onData)})}
async function signer(label){const secret=await hidden(`${label} private key: `),account=createAccount(secret.startsWith('0x')?secret:`0x${secret}`);return{account,client:createClient({chain,account})}}
const read=(client,fn,args=[])=>client.readContract({address:CONTRACT,functionName:fn,args,stateStatus:'finalized',jsonSafeReturn:true});
async function write(s,label,fn,args){const fees=await s.client.estimateTransactionFees({leaderTimeunitsAllocation:300n,validatorTimeunitsAllocation:600n});const hash=await s.client.writeContract({account:s.account,address:CONTRACT,functionName:fn,args,value:0n,fees:{distribution:fees.distribution,feeValue:fees.feeValue}});console.log(`${label}.tx=${hash}`);const receipt=await s.client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:3000,retries:600,fullTransaction:false}),tx=await s.client.getTransaction({hash});console.log(`${label}.execution=${receipt?.txExecutionResultName||'unknown'} consensus=${tx.result_name||tx.result}`);return hash}
const author=await signer('graph author'),observer=await signer('independent observer');
console.log(`pre.workspace=${JSON.stringify(await read(author.client,'get_workspace',[wid]))}`);console.log(`pre.root=${JSON.stringify(await read(author.client,'get_claim',[c1]))}`);console.log(`pre.child=${JSON.stringify(await read(author.client,'get_claim',[c2]))}`);
await write(observer,'cross_object_notice','assess_notice',[wid,'27516793','37086429']);console.log(`after_cross_object.root=${JSON.stringify(await read(author.client,'get_claim',[c1]))}`);console.log(`cross_object.assessment=${JSON.stringify(await read(author.client,'get_assessment',[1]))}`);
await write(observer,'assess_valid_retraction','assess_notice',[wid,'27516793','28515760']);console.log(`impact.root=${JSON.stringify(await read(author.client,'get_claim',[c1]))}`);console.log(`impact.child=${JSON.stringify(await read(author.client,'get_claim',[c2]))}`);console.log(`valid.assessment=${JSON.stringify(await read(author.client,'get_assessment',[2]))}`);
await write(observer,'replay_notice','assess_notice',[wid,'27516793','28515760']);console.log(`after_replay.counts=${JSON.stringify(await read(author.client,'get_counts'))}`);
await write(author,'add_replacement','add_citation',[c1,'10969679']);const repaired=await read(author.client,'get_claim',[c1]);console.log(`replacement.root=${JSON.stringify(repaired)}`);
await write(observer,'reassess_repaired_branch','reassess_claim',[c1,Number(repaired.revision)]);console.log(`final.workspace=${JSON.stringify(await read(author.client,'get_workspace',[wid]))}`);console.log(`final.root=${JSON.stringify(await read(author.client,'get_claim',[c1]))}`);console.log(`final.child=${JSON.stringify(await read(author.client,'get_claim',[c2]))}`);console.log(`final.counts=${JSON.stringify(await read(author.client,'get_counts'))}`);
