#!/usr/bin/env node
import{createAccount,createClient}from'../frontend/node_modules/genlayer-js/dist/index.js';import{studioDevnet}from'../frontend/node_modules/genlayer-js/dist/chains/index.js';
const CONTRACT=process.argv[2],wid=Number(process.argv[3]||1),c1=Number(process.argv[4]||1),c2=Number(process.argv[5]||2);if(!/^0x[0-9a-fA-F]{40}$/.test(CONTRACT||''))throw Error('contract address required');
const chain={...studioDevnet,id:61997,name:'Studio Next',rpcUrls:{default:{http:['https://studio-next.genlayer.com/api']}}};
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');let value='';const done=()=>{process.stdin.off('data',onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==='\u0003'){done();reject(Error('Interrupted'));return}if(ch==='\r'||ch==='\n'){done();process.stdout.write('\n');resolve(value.trim());return}if(ch==='\u007f'||ch==='\b')value=value.slice(0,-1);else value+=ch}};process.stdin.on('data',onData)})}
const secret=await hidden('independent observer private key: '),account=createAccount(secret.startsWith('0x')?secret:`0x${secret}`),client=createClient({chain,account});
const read=(fn,args=[])=>client.readContract({address:CONTRACT,functionName:fn,args,stateStatus:'finalized',jsonSafeReturn:true});
let child=await read('get_claim',[c2]);console.log(`pre.child=${JSON.stringify(child)}`);
if(child.status!=='CURRENT'){const fees=await client.estimateTransactionFees({leaderTimeunitsAllocation:300n,validatorTimeunitsAllocation:600n});const hash=await client.writeContract({account,address:CONTRACT,functionName:'reassess_claim',args:[c2,Number(child.revision)],value:0n,fees:{distribution:fees.distribution,feeValue:fees.feeValue}});console.log(`reassess_child.tx=${hash}`);const receipt=await client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:3000,retries:600,fullTransaction:false}),tx=await client.getTransaction({hash});console.log(`reassess_child.execution=${receipt?.txExecutionResultName||'unknown'} consensus=${tx.result_name||tx.result}`)}
const protocol=await read('get_protocol'),workspace=await read('get_workspace',[wid]),root=await read('get_claim',[c1]);child=await read('get_claim',[c2]);const counts=await read('get_counts');
console.log(`final.protocol=${JSON.stringify(protocol)}`);console.log(`final.workspace=${JSON.stringify(workspace)}`);console.log(`final.root=${JSON.stringify(root)}`);console.log(`final.child=${JSON.stringify(child)}`);console.log(`final.counts=${JSON.stringify(counts)}`);
if(workspace.status!=='SEALED'||root.status!=='CURRENT'||child.status!=='CURRENT'||root.support_revision!==root.revision||child.support_revision!==child.revision)throw Error('FINAL_STATE_INVARIANT_FAILED');
